
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:3caf81ed043761bafdb86956465dbe70d4c3d26449687c9fd1deb57bd5d53e5b
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:86bfc860ce4b851073a47b6e271a4c12a32ed8279a6d11478ea115178a1e198c
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:55da4ff9b10cbcdf8cbaee17225eb8ff854fee4b3e274014a1e05200d81db3de

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:86bfc860ce4b851073a47b6e271a4c12a32ed8279a6d11478ea115178a1e198c
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3caf81ed043761bafdb86956465dbe70d4c3d26449687c9fd1deb57bd5d53e5b
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
