
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:b72867614a7497e5f843ea1df8a2d5b6242615ae256bfb3768c2df55a7c15ca5
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:3b5972aa05f7a561f7c1f35a4753c0bcc93be6ccf20cc112f140f4d0adcd1931
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:7f6ba06c2f65b8ef8cb3511b81aa75e2b973a41133396cc3467afbd95f23ce0e

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3b5972aa05f7a561f7c1f35a4753c0bcc93be6ccf20cc112f140f4d0adcd1931
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b72867614a7497e5f843ea1df8a2d5b6242615ae256bfb3768c2df55a7c15ca5
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
