---
# microshift-start tasks

- name: check if microshift has run
  ansible.builtin.shell: systemctl show -p ActiveEnterTimestampMonotonic microshift | awk -F"=" '{print $2}'
  register: microshift_active
  ignore_errors: true

- block:
  - name: find microshift cleanup script
    ansible.builtin.find:
      paths: /usr/bin
      patterns:
        - '.*microshift.*cleanup.*'
        - '.*cleanup.*microshift.*'
      use_regex: yes
    register: find_cleanup

  - name: set microshift_cleanup_bin variable
    set_fact:
      microshift_cleanup_bin: "{{ find_cleanup.files[0].path if find_cleanup.files }}"

  - name: cleanup microshift data
    become: yes
    ansible.builtin.shell: echo 1 | {{ microshift_cleanup_bin }} --all
  when:
    - cleanup_microshift | default('true') | bool
    - microshift_active.stdout | int != 0

- name: disable microshift service
  become: yes
  ansible.builtin.systemd:
    name: microshift
    state: stopped
    enabled: no

- name: create .kube home dir
  ansible.builtin.file:
    path: ~/.kube/
    state: directory

- name: reboot machine
  become: yes
  ansible.builtin.reboot:
    reboot_timeout: 600

- name: initialize results directory
  include_tasks: roles/common/tasks/results-dir.yml

- name: record post-install disk utilization
  vars:
    filename: disk1.txt
  include_tasks: roles/common/tasks/disk.yml
  loop: "{{ du_dirs }}"

- name: Pause for 60 seconds for steady state post reboot
  ansible.builtin.pause:
    seconds: 60

- name: pbench recording start
  become: yes
  block:
  - name: source pbench-agent & register-tool-set
    ansible.builtin.shell: source /etc/profile.d/pbench-agent.sh && pbench-register-tool-set

  - name: set new pidstat interval
    ansible.builtin.shell: source /etc/profile.d/pbench-agent.sh && pbench-register-tool --name=pidstat -- --interval={{ sample_interval }}

  - name: start pbench-user-benchmark recording
    ansible.builtin.shell: source /etc/profile.d/pbench-agent.sh && pbench-user-benchmark --config=microshift -- sleep {{ pbench_record_duration }}
    async: "{{ pbench_record_duration|int * 2 }}"
    poll: 0
    register: pbench_user_benchmark_result

  - name: Pause for 60 seconds to gather steady state for pbench tool recording
    ansible.builtin.pause:
      seconds: 60
  when: install_pbench | bool
  environment:
    PBENCH_TOOL_DATA_SINK: localhost:8081

- name: check for cadvisor
  ansible.builtin.command: which cadvisor
  register: cadvisor_check
  ignore_errors: true

- name: record network measurement start epoch
  ansible.builtin.command: date +%s
  register: network_start_epoch

- name: measure microshift service boot time
  include_tasks: roles/common/tasks/boot.yml
  vars:
    boot_output_filename: "boot0.txt"
    cleanup_microshift: false
    reboot: false

- name: create service account task(s)
  include_tasks: roles/create-service-account/tasks/main.yml

- name: finish pbench capture
  become: yes
  block:
  - name: check on pbench-user-benchmark status
    ansible.builtin.async_status:
      jid: "{{ pbench_user_benchmark_result.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 240
    delay: 15

  - name: source pbench-agent & move results
    ansible.builtin.shell: source /etc/profile.d/pbench-agent.sh && pbench-move-results
    ignore_errors: yes
  when: install_pbench | bool
  environment:
    PBENCH_USER: microshift

- name: record fully running disk utilization
  vars:
    filename: disk2.txt
  include_tasks: roles/common/tasks/disk.yml
  loop: "{{ du_dirs }}"

- name: capture container image sizes
  block:
    - name: copy crio-df script to remote host
      become: yes
      ansible.builtin.copy:
        src: roles/common/tasks/files/crio-df.py
        dest: /tmp/crio-df.py
        mode: '0755'

    - name: run crio-df script
      become: yes
      ansible.builtin.command: python3 /tmp/crio-df.py -v
      register: crio_df

    - name: save container image sizes to results
      ansible.builtin.copy:
        content: "{{ crio_df.stdout }}"
        dest: "{{ results_dir }}/images.txt"
      delegate_to: localhost

- name: record network measurement end epoch
  ansible.builtin.command: date +%s
  register: network_end_epoch

- name: resolve prometheus network query settings
  ansible.builtin.set_fact:
    prom_network_endpoint: >-
      {{
        prometheus_query_endpoint | default(
          'http://' ~
          (
            (
              hostvars[(groups['logging'] | default([]) | first)].ansible_host
              | default((groups['logging'] | default([]) | first))
            )
            if (groups['logging'] | default([]) | length > 0)
            else 'zen3'
          )
          ~ ':' ~ (prometheus_port | default(9091) | string),
          true
        )
      }}
    prom_network_device: "{{ network_device | default(ansible_default_ipv4.interface | default('enp5s0'), true) }}"
    prom_network_instance: "{{ inventory_hostname }}:9100"
  when: prometheus_logging | bool

- name: query prometheus for network transfer
  block:
    - name: run prometheus network query
      ansible.builtin.command: >
        python3 roles/common/tasks/files/prom-network-query.py
        --prometheus {{ prom_network_endpoint }}
        --instance {{ prom_network_instance }}
        --device {{ prom_network_device }}
        {{ network_start_epoch.stdout }}
        {{ network_end_epoch.stdout }}
      register: prom_network
      delegate_to: localhost

    - name: save network data to results
      ansible.builtin.copy:
        content: "{{ prom_network.stdout }}"
        dest: "{{ results_dir }}/network.txt"
      delegate_to: localhost
  when: prometheus_logging | bool
